// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxbIrBz1s5rv2wtAoI1qVtqWEptqgay4',
    appId: '1:759600958667:android:f2ab0487891d5a80cf5f4e',
    messagingSenderId: '759600958667',
    projectId: 'flutter-auth-2a7a2',
    storageBucket: 'flutter-auth-2a7a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPy9B5ToWjHFXrP7vyoo67OyAE2GVZJ8E',
    appId: '1:759600958667:ios:79fb9dea3aa8f669cf5f4e',
    messagingSenderId: '759600958667',
    projectId: 'flutter-auth-2a7a2',
    storageBucket: 'flutter-auth-2a7a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPy9B5ToWjHFXrP7vyoo67OyAE2GVZJ8E',
    appId: '1:759600958667:ios:79fb9dea3aa8f669cf5f4e',
    messagingSenderId: '759600958667',
    projectId: 'flutter-auth-2a7a2',
    storageBucket: 'flutter-auth-2a7a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WWN0YNH4xejL9Y9oyo06peS_32rZky4',
    appId: '1:759600958667:web:874778ab3ff86fc9cf5f4e',
    messagingSenderId: '759600958667',
    projectId: 'flutter-auth-2a7a2',
    authDomain: 'flutter-auth-2a7a2.firebaseapp.com',
    storageBucket: 'flutter-auth-2a7a2.firebasestorage.app',
  );
}
